import { Brand, BrandAsset, BrandCollection } from '@/types/brand';

export const createDemoBrand = (userId: string): Omit<Brand, 'id' | 'created_at' | 'updated_at'> => ({
  user_id: userId,
  name: "Sample Coffee Shop",
  description: "A modern artisan coffee shop brand - explore this demo to see how Virtura works!",
  logo_url: null,
  brand_colors: {
    primary: "#6F4E37",
    secondary: "#F4E8D8",
    accent: "#E8B86D",
  },
  brand_fonts: {
    heading: "Playfair Display",
    body: "Inter",
  },
  tone_of_voice: "Warm, inviting, artisanal, community-focused. We speak to coffee lovers who appreciate quality and sustainability.",
  target_audience: "Coffee enthusiasts aged 25-45 who value quality, sustainability, and community",
  industry: "Food & Beverage",
  social_handles: {
    instagram: "@sample_coffee_shop",
    tiktok: "@samplecoffee",
    twitter: "@SampleCoffee",
  },
  website_url: "https://sample-coffee-shop.example.com",
  is_active: true,
  organization_id: null,
});

export const createDemoCollections = (brandId: string, userId: string): Omit<BrandCollection, 'id' | 'created_at' | 'updated_at'>[] => [
  {
    brand_id: brandId,
    user_id: userId,
    name: "Summer Campaign 2025",
    description: "Iced coffee and cold brew promotions for the summer season",
    collection_type: "campaign",
    color_label: "#E8B86D",
    is_smart_folder: false,
    smart_rules: null,
    parent_collection_id: null,
    sort_order: 0,
  },
  {
    brand_id: brandId,
    user_id: userId,
    name: "Product Photos",
    description: "Professional shots of our coffee products and merchandise",
    collection_type: "product",
    color_label: "#6F4E37",
    is_smart_folder: false,
    smart_rules: null,
    parent_collection_id: null,
    sort_order: 1,
  },
  {
    brand_id: brandId,
    user_id: userId,
    name: "Social Media Ready",
    description: "Content optimized for Instagram & TikTok",
    collection_type: "custom",
    color_label: "#F4E8D8",
    is_smart_folder: true,
    smart_rules: { tags: ["instagram", "tiktok", "social"] },
    parent_collection_id: null,
    sort_order: 2,
  },
  {
    brand_id: brandId,
    user_id: userId,
    name: "Top Performers",
    description: "Our highest-engagement content",
    collection_type: "custom",
    color_label: "#10B981",
    is_smart_folder: true,
    smart_rules: null,
    parent_collection_id: null,
    sort_order: 3,
  },
];

export const createDemoAssets = (brandId: string, collectionId: string, userId: string): Omit<BrandAsset, 'id' | 'created_at' | 'updated_at'>[] => [
  {
    brand_id: brandId,
    collection_id: collectionId,
    user_id: userId,
    title: "Iced Latte Hero Shot",
    description: "Beautiful iced latte on wooden table with natural lighting - perfect for Instagram feed",
    asset_type: "image",
    file_url: "/lovable-uploads/demo-iced-latte.jpg",
    thumbnail_url: "/lovable-uploads/demo-iced-latte.jpg",
    generation_prompt: "Professional product photography of iced latte coffee, wooden table, natural daylight, Instagram aesthetic, warm tones",
    ai_model_used: "Flux Pro",
    dimensions: { width: 1024, height: 1024, aspectRatio: "1:1" },
    file_size: 245000,
    format: "jpg",
    tags: ["instagram", "product", "summer", "iced", "latte"],
    labels: { campaign: "Summer 2025", status: "approved" },
    metadata: { shoot_date: "2025-06-15", photographer: "Demo" },
    usage_count: 42,
    performance_score: 9.2,
    is_favorite: true,
    is_archived: false,
  },
  {
    brand_id: brandId,
    collection_id: collectionId,
    user_id: userId,
    title: "Cold Brew Pour",
    description: "Action shot of cold brew being poured over ice - dynamic and engaging",
    asset_type: "video",
    file_url: "/lovable-uploads/demo-cold-brew-pour.mp4",
    thumbnail_url: "/lovable-uploads/demo-cold-brew-thumb.jpg",
    generation_prompt: "Slow motion video of cold brew coffee being poured over ice in a glass, dramatic lighting",
    ai_model_used: "Runway Gen-3",
    dimensions: { width: 1080, height: 1920, aspectRatio: "9:16" },
    file_size: 3200000,
    format: "mp4",
    tags: ["tiktok", "video", "product", "cold-brew", "social"],
    labels: { campaign: "Summer 2025", status: "published" },
    metadata: { duration: "15s", platform: "TikTok" },
    usage_count: 128,
    performance_score: 8.7,
    is_favorite: true,
    is_archived: false,
  },
  {
    brand_id: brandId,
    collection_id: collectionId,
    user_id: userId,
    title: "Barista Crafting Latte Art",
    description: "Behind-the-scenes content showing our skilled baristas at work",
    asset_type: "image",
    file_url: "/lovable-uploads/demo-latte-art.jpg",
    thumbnail_url: "/lovable-uploads/demo-latte-art.jpg",
    generation_prompt: "Barista pouring latte art, close-up shot, warm cafe ambiance, authentic atmosphere",
    ai_model_used: "DALL-E 3",
    dimensions: { width: 1024, height: 1024, aspectRatio: "1:1" },
    file_size: 198000,
    format: "jpg",
    tags: ["instagram", "behind-the-scenes", "barista", "craft"],
    labels: { content_type: "lifestyle", status: "approved" },
    metadata: { location: "Main Store" },
    usage_count: 67,
    performance_score: 8.1,
    is_favorite: false,
    is_archived: false,
  },
  {
    brand_id: brandId,
    collection_id: collectionId,
    user_id: userId,
    title: "Coffee Bean Close-Up",
    description: "Macro photography of freshly roasted coffee beans - showcases quality",
    asset_type: "image",
    file_url: "/lovable-uploads/demo-coffee-beans.jpg",
    thumbnail_url: "/lovable-uploads/demo-coffee-beans.jpg",
    generation_prompt: "Macro photography of roasted coffee beans, rich brown colors, high detail, professional food photography",
    ai_model_used: "Midjourney v6",
    dimensions: { width: 1024, height: 1024, aspectRatio: "1:1" },
    file_size: 312000,
    format: "jpg",
    tags: ["product", "detail", "quality", "instagram"],
    labels: { product_line: "Premium Roast", status: "approved" },
    metadata: { bean_origin: "Colombia" },
    usage_count: 34,
    performance_score: 7.9,
    is_favorite: false,
    is_archived: false,
  },
  {
    brand_id: brandId,
    collection_id: collectionId,
    user_id: userId,
    title: "Cozy Cafe Corner",
    description: "Lifestyle shot of our cafe interior - warm and inviting atmosphere",
    asset_type: "image",
    file_url: "/lovable-uploads/demo-cafe-interior.jpg",
    thumbnail_url: "/lovable-uploads/demo-cafe-interior.jpg",
    generation_prompt: "Cozy modern cafe interior, warm lighting, wooden furniture, plants, inviting atmosphere",
    ai_model_used: "Stable Diffusion XL",
    dimensions: { width: 1024, height: 768, aspectRatio: "4:3" },
    file_size: 278000,
    format: "jpg",
    tags: ["lifestyle", "interior", "ambiance", "instagram"],
    labels: { content_type: "lifestyle", location: "Main Store" },
    metadata: { shoot_date: "2025-05-20" },
    usage_count: 56,
    performance_score: 8.4,
    is_favorite: true,
    is_archived: false,
  },
];
