project_id = "ujaoziqnxhjqlmnvlxav"

[functions.generate-image-replicate]
verify_jwt = true

[functions.generate-avatar-real]
verify_jwt = true

[functions.voice-preview]
verify_jwt = true

[functions.generate-avatar]
verify_jwt = true

[functions.generate-avatar-hf]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.voice-generate]
verify_jwt = true

[functions.video-generate]
verify_jwt = true

[functions.video-sync]
verify_jwt = true

[functions.upload-avatar]
verify_jwt = true

[functions.video-generate-multi]
verify_jwt = true

[functions.video-generate-simple]
verify_jwt = true

[functions.cleanup-heygen-avatars]
verify_jwt = true

[functions.video-generate-direct]
verify_jwt = true

[functions.video-engine-pro]
verify_jwt = true

[functions.voice-tts]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.voice-transcribe-whisper]
verify_jwt = true
