-- Admin role grants skipped - original users do not exist in new project
-- To assign admin role after creating your account:
-- INSERT INTO public.user_roles (user_id, role) VALUES ('<your-user-id>', 'admin') ON CONFLICT (user_id, role) DO NOTHING;
